"""add_claim_model

Revision ID: 003fc1103fdc
Revises: ac6e7820b704
Create Date: 2025-11-23 22:45:05.208934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '003fc1103fdc'
down_revision: Union[str, Sequence[str], None] = 'ac6e7820b704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('date_of_service', sa.Date(), nullable=False),
    sa.Column('cpt_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('diagnosis_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('allowed_amount', sa.Float(), nullable=False),
    sa.Column('provider_npi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['eligibility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim')
    # ### end Alembic commands ###
