"""add_total_savings

Revision ID: 40ad7a172774
Revises: 4db8b4fb78d0
Create Date: 2025-11-24 01:04:23.055483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '40ad7a172774'
down_revision: Union[str, Sequence[str], None] = '4db8b4fb78d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eligibility', sa.Column('total_savings', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eligibility', 'total_savings')
    # ### end Alembic commands ###
