"""add_baseline_savings_tracking

Revision ID: 44803cd20830
Revises: 8dd24c5372dd
Create Date: 2025-11-24 01:29:15.101252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '44803cd20830'
down_revision: Union[str, Sequence[str], None] = '8dd24c5372dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referralevent', sa.Column('service_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('referralevent', sa.Column('ordering_provider_npi', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('referralevent', sa.Column('baseline_npi', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('referralevent', sa.Column('baseline_allowed', sa.Float(), nullable=True))
    op.add_column('referralevent', sa.Column('redirected_npi', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('referralevent', sa.Column('redirected_allowed', sa.Float(), nullable=True))
    op.add_column('referralevent', sa.Column('member_cost_share', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('referralevent', sa.Column('plan_cost_baseline', sa.Float(), nullable=True))
    op.add_column('referralevent', sa.Column('plan_cost_redirected', sa.Float(), nullable=True))
    op.add_column('referralevent', sa.Column('net_savings', sa.Float(), nullable=True))
    op.drop_column('referralevent', 'provider_npi')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referralevent', sa.Column('provider_npi', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('referralevent', 'net_savings')
    op.drop_column('referralevent', 'plan_cost_redirected')
    op.drop_column('referralevent', 'plan_cost_baseline')
    op.drop_column('referralevent', 'member_cost_share')
    op.drop_column('referralevent', 'redirected_allowed')
    op.drop_column('referralevent', 'redirected_npi')
    op.drop_column('referralevent', 'baseline_allowed')
    op.drop_column('referralevent', 'baseline_npi')
    op.drop_column('referralevent', 'ordering_provider_npi')
    op.drop_column('referralevent', 'service_name')
    # ### end Alembic commands ###
