"""add_opted_in_date

Revision ID: 4db8b4fb78d0
Revises: f05d3e6e26d9
Create Date: 2025-11-24 00:44:05.932706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4db8b4fb78d0'
down_revision: Union[str, Sequence[str], None] = 'f05d3e6e26d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eligibility', sa.Column('opted_in_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eligibility', 'opted_in_date')
    # ### end Alembic commands ###
