"""add_cpt_npi_exception

Revision ID: 8dd24c5372dd
Revises: 40ad7a172774
Create Date: 2025-11-24 01:22:02.815725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8dd24c5372dd'
down_revision: Union[str, Sequence[str], None] = '40ad7a172774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cptnpiexception',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('cpt_bundle_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpt_list', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('npi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost_share_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('member_cost_share', sa.Float(), nullable=False),
    sa.Column('avg_savings', sa.Float(), nullable=False),
    sa.Column('p10_savings', sa.Float(), nullable=False),
    sa.Column('episode_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cptapprovalrule', sa.Column('requires_approval', sa.Boolean(), nullable=False))
    op.add_column('cptapprovalrule', sa.Column('auto_approve_threshold', sa.Float(), nullable=True))
    op.drop_column('cptapprovalrule', 'facility_npi')
    op.drop_column('cptapprovalrule', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cptapprovalrule', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('cptapprovalrule', sa.Column('facility_npi', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('cptapprovalrule', 'auto_approve_threshold')
    op.drop_column('cptapprovalrule', 'requires_approval')
    op.drop_table('cptnpiexception')
    # ### end Alembic commands ###
