"""add_risk_tier

Revision ID: ac6e7820b704
Revises: 
Create Date: 2025-11-23 21:58:05.322295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added import


# revision identifiers, used by Alembic.
revision: str = 'ac6e7820b704'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eligibility', sa.Column('risk_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="Low"))
    op.add_column('memberinteraction', sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="legacy"))
    op.add_column('memberinteraction', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('memberinteraction', 'inbound_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memberinteraction', 'inbound_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('memberinteraction', 'content')
    op.drop_column('memberinteraction', 'message_type')
    op.drop_column('eligibility', 'risk_tier')
    # ### end Alembic commands ###
