"""add_zip_codes

Revision ID: bc191bd04c35
Revises: 003fc1103fdc
Create Date: 2025-11-23 23:10:52.266032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bc191bd04c35'
down_revision: Union[str, Sequence[str], None] = '003fc1103fdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eligibility', sa.Column('zip_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eligibility', 'zip_code')
    # ### end Alembic commands ###
